version: 2.1
orbs:
  # New change
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  # different jobs are calles later in the workflows sections
  aws-cli: circleci/aws-cli@2.0.6
jobs:
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          aws-region: AWS_REGION
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      
      # install dependencies in both apps
      - run:
          name: install server dependencies
          command: |
            npm run backend:install
      - run:
          name: install UI dependencies
          command: |
            npm run frontend:install
      - run:
          name: build the server 
          command: |
            cd reactnd-contacts-server && npm run build
      - run:
          name: build the UI
          command: |
            cd reactnd-contacts-complete && npm run build
workflows:
  aws-cli:
    jobs:
      - aws-cli-cred-setup:
          context: aws